### ISSUE TITLE
"Failed to load the native TensorFlow runtime"

### ISSUE THREAD

**Issue by RicedeKrispy** [AltschulerWu-Lab/scScope#5]
When I try to first 'import scscope as DeepImute', that error is thrown. Any advice?

**Comment by fbao-fudan** [comment]
Thanks for your interest in our work. This is likely to be caused by wrong configuration of TensorFlow.

If you are using GPU, you can try update tensorflow, cuda, cudnn all to the latest version. Some tensorflow versions can only work with specific version of cuda and cudnn. You can check the software requirement in this link https://www.tensorflow.org/install/gpu for more information.

If this still happens, I suggest you install tensorflow CPU version instead. Using "pip install tensorflow"
